= Student CRM API Documentation

v2.0, 20.11.2024

== Introduction
This documentation provides an overview of the Student CRM API, including the available endpoints, their use cases, and example requests/responses.

=== Change History
[cols="1,3"]
|===
| Version | Description
| 1.0    | Start version
| 2.0    | Final version :)
|===


== Service Overview

This service can manage students and courses. You can perform basic CRUD operations on both. Additionally, you can manage the courses in which students are enrolled.


== Domains

=== Student


**Attributes**:

- `id`: Unique identifier of the student
- `firstname`: First name of the student
- `lastname`: Last name of the student
- `email`: Unique email address of the student
- `courses`: List of Courses enrolled

=== Course

**Attributes**:

- `id`: Unique identifier of the course
- `name`: Name of the course
- `students`: List of students in the course

== Endpoints

=== Student Resource

==== 1. Get a paginated list of students
`GET /api/student`

*Query Parameters:*

- `page` (optional, integer): The page number for pagination +
- `rowsPerPage` (optional, integer): The number of records per page +
- `search` (required, string): Search keyword +
- `sortField` (required, string): Field by which to sort +
- `sortOrder` (required, string): Order of sorting (asc or desc) +

Response: 200 OK +
Content: Array of StudentDTO
```json
[
    {
      "id": 1,
      "firstname": "Han",
      "lastname": "Solo",
      "email": "han.solo@example.com",
      "courses": [
          {
            "id": 3,
            "name": "Smuggling for Beginners"
          },
          {
            "id": 4,
            "name": "Piloting"
          }
      ]
    },
    {
      "id": 2,
      "firstname": "Boba",
      "lastname": "Fett",
      "email": "boba.fett@example.com",
      "courses": []
    }
]
```

==== 2. Get all students
`GET /api/student/all`

Response: 200 OK +
Content: Array of StudentDTO
```json
[
    {
      "id": 1,
      "firstname": "Han",
      "lastname": "Solo",
      "email": "han.solo@example.com",
      "courses": [
          {
            "id": 3,
            "name": "Smuggling for Beginners"
          },
          {
            "id": 4,
            "name": "Piloting"
          }
      ]
    },
    {
      "id": 2,
      "firstname": "Boba",
      "lastname": "Fett",
      "email": "boba.fett@example.com",
      "courses": []
    }
]
```

==== 3. Count students
`GET /api/student/count`

Query Parameters:

- `search` (required, string): Search keyword

Response: 200 OK +
Content: Integer representing the count of students
```json
2
```


==== 4. Create a student
`POST /api/student/create`

*Request Body:* StudentCreateUpdateDTO +
Example:
```json
{
  "firstname": "Han",
  "lastname": "Solo",
  "email": "han.solo@example.com"
}
```

Response: 200 OK +
Content: Created StudentDTO
```json
{
  "id": 3,
  "firstname": "Han",
  "lastname": "Duo",
  "email": "han.duo@example.com",
  "courses": []
}
```

==== 5. Delete students
`DELETE /api/student/delete`

*Request Body:* Array of integers (student IDs to delete)
```json
[
  1, 3
]
```

Response: 204 No Content

==== 6. Get a student by ID
`GET /api/student/{id}`

Path Parameters: +

- `id` (required, integer): ID of the student

Response: 200 OK +
Content: StudentDTO
```json
{
  "id": 1,
  "firstname": "Han",
  "lastname": "Solo",
  "email": "han.solo@example.com",
  "courses": [
      {
        "id": 3,
        "name": "Smuggling for Beginners"
      }
  ]
}
```


==== 7. Assign courses to a student
`PUT /api/student/{id}/assignCourses`

*Path Parameters:*

- `id` (required, integer): ID of the student

*Request Body:* Array of integers (course IDs to assign).

Response: 200 OK +
Content: Array of CourseDTO +
It returns the list of assigned courses (excluding students).
```json
[
    {
        "id": 3,
        "name": "Smuggling for Beginners",
        "students": []
    },
    {
        "id": 4,
            "name": "Piloting",
        "students": []
    },
    {
        "id": 1,
        "name": "Starship Engineering",
        "students": []
    }
]
```


==== 8. Update a student
`PUT /api/student/{id}/update`

*Path Parameters:*

- `id` (required, integer): ID of the student

*Request Body:* StudentCreateUpdateDTO +
Example:
```json
{
  "firstname": "Han",
  "lastname": "Trio",
  "email": "han.trio@newemail.com"
}
```
The ID needs to exist. The updated email can't be an in the database existing one (unique attribute). It Updates an existing student's information (**excluding courses**)


Response: 200 OK +
Content: Updated StudentDTO
```json
{
  "id": 1,
  "firstname": "Han",
  "lastname": "Duo",
  "email": "han.duo@newemail.com",
  "courses": [
      {
        "id": 3,
        "name": "Smuggling for Beginners"
      }
  ]
}
```


=== Course Resource

==== 1. Get a paginated list of courses
`GET /api/course`

*Query Parameters:* +
- `page` (optional, integer): The page number for pagination. +
- `rowsPerPage` (optional, integer): The number of records per page. +
- `search` (required, string): Search keyword. +
- `sortField` (required, string): Field by which to sort. +
- `sortOrder` (required, string): Order of sorting (`asc` or `desc`). +

*Response:* `200 OK` +
Content: Array of `CourseDTO`.

```json
[
  {
    "id": 1,
    "name": "Starcraft Engineering",
    "students": [
        {
            "id": 1,
            "firstname": "Han",
            "lastname": "Solo",
            "email": "han.solo@example.com"
        },
        {
            "id": 2,
            "firstname": "Boba",
            "lastname": "Fett",
            "email": "boba.fett@example.com"
        }
    ]
  },
  {
    "id": 2,
    "name": "Piloting 101",
    "students":[]
  }
]
```

==== 3. Count courses
`GET /api/course/count`

*Query Parameters:* +
- `search` (required, string): Search keyword. +

*Response:* 200 OK +
Content: Integer representing the count of courses.

```json
7
```

==== 4. Create a course
`POST /api/course/create`

*Request Body:* CourseCreateUpdateDTO +
Example:
```json
{
  "name": "Starship Engineering"
}
```
Response: 200 OK +
Content: Created CourseDTO.
```json
{
  "id": 1,
  "name": "Starship Engineering",
  "students":[]
}
```

==== 5. Delete courses
`DELETE /api/course/delete`

Request Body: Array of integers (course IDs to delete). +
```json
[
  7, 10, 4
]
```
Response: 204 No Content +

==== 6. Get a course by ID
`GET /api/course/{id}`

Path Parameters:

- `id` (required, integer): ID of the course.

Response: 200 OK +
Content: CourseDTO
```json
{
    "id": 1,
    "name": "Starcraft Engineering",
    "students": [
        {
            "id": 1,
            "firstname": "Han",
            "lastname": "Solo",
            "email": "han.solo@example.com"
        },
        {
            "id": 2,
            "firstname": "Boba",
            "lastname": "Fett",
            "email": "boba.fett@example.com"
        }
    ]
  }
```

==== 7. Assign students to a course
`PUT /api/course/{id}/assignStudents`

Path Parameters:

- `id` (required, integer): ID of the course. +

Request Body: Array of integers (student IDs to assign).
```json
[
  3, 4, 5
]
```
Response: 200 OK +
Content: Array of StudentDTO. +
It returns the list of assigned students (excluding courses).
```json
[
    {
      "id": 1,
      "firstname": "Han",
      "lastname": "Solo",
      "email": "han.solo@example.com",
      "courses": []
    },
    {
      "id": 2,
      "firstname": "Boba",
      "lastname": "Fett",
      "email": "boba.fett@example.com",
      "courses": []
    }
]
```



==== 8. Update a course
`PUT /api/course/{id}/update`

Path Parameters: +

- `id` (required, integer): ID of the course.

Request Body: CourseCreateUpdateDTO +
Example:
```json
{
  "name": "Spacecraft Engineering"
}
```

Response: 200 OK +
Content: Updated CourseDTO.
```json
{
    "id": 1,
    "name": "Ship Engineering",
    "students": [
        {
            "id": 1,
            "firstname": "Han",
            "lastname": "Solo",
            "email": "han.solo@example.com"
        },
        {
            "id": 2,
            "firstname": "Boba",
            "lastname": "Fett",
            "email": "boba.fett@example.com"
        }
    ]
}
```
