
= Student CRM API Documentation

v1.0, 19.10.2024

== Introduction
This documentation provides an overview of the Student CRM API, including the available endpoints, their use cases, and example requests/responses.


=== Change History
[cols="1,3"]
|===
| Version | Description
| 1.0    | Start version
|===


== Service Overview

This service can manage students and courses. You can perform basic CRUD operations on both. Additionally, you can manage the courses in which students are enrolled.


== Domains

=== Student


**Attributes**:

- `id`: Unique identifier of the student
- `firstname`: First name of the student
- `lastname`: Last name of the student
- `email`: Unique email address of the student
- `courses`: List of Courses enrolled

=== Course

**Attributes**:

- `id`: Unique identifier of the course
- `name`: Name of the course
- `students`: List of students in the course

== APIs

---
=== Student Endpoints

---
==== Get All Students
**Description**: Retrieves a list of all students.

**Endpoint**: `GET /api/student/all`

**Example Response**:
[source,json]
----
[
    {
      "id": 1,
      "firstname": "Han",
      "lastname": "Solo",
      "email": "han.solo@example.com",
      "courses": [
          {
            "id": 3,
            "name": "Smuggling for Beginners"
          },
          {
            "id": 4,
            "name": "Piloting"
          }
      ]
    },
    {
      "id": 2,
      "firstname": "Boba",
      "lastname": "Fett",
      "email": "boba.fett@example.com",
      "courses": []
    }
]
----

---
==== Find Students by Name or Email
**Description**: Retrieves a list of students by a search term (name or email).

**Endpoint**: `GET /api/student?page={pageNumber}&limit={limit}&search={searchTerm}`



**Example Response**:
[source,json]
----
[
    {
      "id": 1,
      "firstname": "Han",
      "lastname": "Solo",
      "email": "han.solo@example.com",
      "courses": [
          {
            "id": 3,
            "name": "Smuggling for Beginners"
          },
          {
            "id": 4,
            "name": "Piloting"
          }
      ]
    },
    {
      "id": 2,
      "firstname": "Boba",
      "lastname": "Fett",
      "email": "boba.fett@example.com",
      "courses": []
    }
]
----



---
==== Get Student by ID
**Description**: Retrieves a student by their ID.

**Endpoint**: `GET /api/student/{id}`



**Example Response**:
[source,json]
----
{
  "id": 1,
  "firstname": "Han",
  "lastname": "Solo",
  "email": "han.solo@example.com",
  "courses": [
      {
        "id": 3,
        "name": "Smuggling for Beginners"
      }
  ]
}
----

---
==== Create Student
**Description**: Creates a new student.

**Endpoint**: `POST /api/student/create`

**Example Request**:
[source,json]
----
{
  "firstname": "Han",
  "lastname": "Solo",
  "email": "han.solo@example.com"
}
----

**Example Response**:
[source,json]
----
{
  "id": 1,
  "firstname": "Han",
  "lastname": "Solo",
  "email": "han.solo@example.com",
  "courses": [
      {
        "id": 3,
        "name": "Smuggling for Beginners"
      }
  ]
}
----


---
==== Update Student
**Description**: Updates an existing student's information (**excluding courses**).

**Endpoint**: `PUT /api/student/{id}/update`

**Example Request**:
[source,json]
----
{
  "firstname": "Han",
  "lastname": "Duo",
  "email": "han.duo@newemail.com"
}
----
The ID needs to exist. The updated email can't be an in the database existing one (unique attribute).

**Example Response**:
[source,json]
----
{
  "id": 1,
  "firstname": "Han",
  "lastname": "Duo",
  "email": "han.duo@newemail.com",
  "courses": [
      {
        "id": 3,
        "name": "Smuggling for Beginners"
      }
  ]
}
----

---
==== Delete Student
**Description**: Deletes a list of students by their ID (if only one student needs to be deleted, pass a list with one ID).

**Endpoint**: `DELETE /api/student/delete`

**Example Request**:
[source,json]
----
[
  1, 3, 4, 7
]
----

**Example Response**:
[source,json]
----
204 No Content
----

---
==== Assign a Student's Courses
**Description**: Assigns a list of courses to a student. The list removes courses that were not in the list before and adds new ones. So the list you provide is always exactly the list of courses a student is enrolled in.

**Endpoint**: `PUT /api/student/{id}/assignCourses`

**Example Request**:
[source,json]
----
[
  3, 5, 1
]
----
The IDs need to exist.

**Example Response**:
[source,json]
----
[
    {
        "id": 5,
        "name": "History",
        "students": []
    },
    {
        "id": 18,
        "name": "Business Management",
        "students": []
    },
    {
        "id": 1,
        "name": "Maths",
        "students": []
    }
]
----
It returns the list of assigned courses (excluding students).

---
---
---
=== Course Endpoints
---
==== Get All Courses
**Description**: Retrieves a list of all courses.

**Endpoint**: `GET /api/course/all`

**Example Request**:
[source,json]
----
GET /api/course/all
----

**Example Response**:
[source,json]
----
[
  {
    "id": 1,
    "name": "Starcraft Engineering",
    "students": [
        {
            "id": 1,
            "firstname": "Han",
            "lastname": "Solo",
            "email": "han.solo@example.com"
        },
        {
            "id": 2,
            "firstname": "Boba",
            "lastname": "Fett",
            "email": "boba.fett@example.com"
        }
    ]
  },
  {
    "id": 2,
    "name": "Piloting 101",
    "students":[]
  }
]
----

---
==== Find Courses by Search Term
**Description**: Retrieves a list of courses by a search term (name).

**Endpoint**: `GET /api/course?page={pageNumber}&limit={limit}&search={searchTerm}`



**Example Response**:
[source,json]
----
[
  {
    "id": 1,
    "name": "Starcraft Engineering",
    "students": [
        {
            "id": 1,
            "firstname": "Han",
            "lastname": "Solo",
            "email": "han.solo@example.com"
        },
        {
            "id": 2,
            "firstname": "Boba",
            "lastname": "Fett",
            "email": "boba.fett@example.com"
        }
    ]
  },
  {
    "id": 2,
    "name": "Piloting 101",
    "students":[]
  }
]
----

---
==== Create Course
**Description**: Creates a new course.

**Endpoint**: `POST /api/course/create`

**Example Request**:
[source,json]
----
{
  "name": "Starship Engineering"
}
----

**Example Response**:
[source,json]
----
{
  "id": 1,
  "name": "Starship Engineering",
  "students": []
}
----

---
==== Update Course
**Description**: Updates an existing course's name.

**Endpoint**: `PUT /api/course/{id}/update`

**Example Request**:
[source,json]
----
{
  "name": "Spacecraft Engineering"
}
----
The ID needs to exist. The updated name can't be an in the database existing one (unique attribute).

**Example Response**:
[source,json]
----
{
    "id": 1,
    "name": "Starcraft Engineering",
    "students": [
        {
            "id": 1,
            "firstname": "Han",
            "lastname": "Solo",
            "email": "han.solo@example.com"
        },
        {
            "id": 2,
            "firstname": "Boba",
            "lastname": "Fett",
            "email": "boba.fett@example.com"
        }
    ]
}
----

---
==== Delete Course
**Description**: Deletes a list of courses by their ID (if only one course needs to be deleted, pass a list with one ID)

**Endpoint**: `DELETE /api/course/delete`

**Example Request**:
[source,json]
----
[
  3, 5, 1
]
----

**Example Response**:
[source,json]
----
204 No Content
----


---
==== Assign a Course's Students
**Description**: Assigns a list of students to a course. The list removes students that were not in the list before and adds new ones. So the list you provide is always exactly the list of students enrolled in the course.

**Endpoint**: `PUT /api/course/{id}/assignStudents`

**Example Request**:
[source,json]
----
[
  3, 5, 1
]
----
The IDs need to exist.

**Example Response**:
[source,json]
----
[
    {
      "id": 1,
      "firstname": "Han",
      "lastname": "Solo",
      "email": "han.solo@example.com",
      "courses": []
    },
    {
      "id": 2,
      "firstname": "Boba",
      "lastname": "Fett",
      "email": "boba.fett@example.com",
      "courses": []
    }
]
----
It returns the list of assigned students (excluding courses).
